channels:
- defaults
- pytorch
dependencies:
- python=3.6.5


- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/17733694
  - azureml-defaults==0.1.0.17733694
  - azureml-pipeline-wrapper==0.1.0.17733694
  - torch==1.3
  - torchvision==0.4.1

name: project_environment

